/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --transform star_destroyer.glb 
Files: star_destroyer.glb [6.24MB] > /Users/lunakepio/x-wing/public/star_destroyer-transformed.glb [1.23MB] (80%)
Author: rubaun (https://sketchfab.com/rubaun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-destroyer-aaa18e14129a461c839877389bd28504
Title: Star Destroyer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Destroyer(props) {
  const { nodes, materials } = useGLTF('./star_destroyer-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, 2, 2000]} scale={80}>
      {/* <directionalLight position={[0, 10, 0]} castShadow intensity={0.5} color={"#f2fafd"} /> */}
      <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.blinn1SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.blinn7SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.blinn9SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.blinn10SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.blinn12SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.blinn2SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.blinn5SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.blinn6SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.blinn8SG} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
      <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.initialShadingGroup} position={[0, 0, -0.578]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.459} />
    </group>
  )
}

useGLTF.preload('./star_destroyer-transformed.glb')
